[metadata]
name = TM_catalyst_framework
version = 0.1.0
author = Dawn Mao
description = A Python-based framework for modeling titanium ureate catalyst structures
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
url = https://github.com/dmao1020/TM_catalyst_framework
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.9
include_package_data = True

[options.packages.find]
where = src

[options.package_data]
TM_catalyst_framework =
    template/*.xyz
